### ISSUE TITLE
Doesn't build with GHC 9.8 (and probably later)

### ISSUE THREAD

**Issue by lolepezy** [well-typed/ixset-typed#32]
```
ixset-typed> configure
ixset-typed> Configuring ixset-typed-0.5.1.0...
ixset-typed> build with ghc-9.8.4
ixset-typed> Preprocessing library for ixset-typed-0.5.1.0..
ixset-typed> Building library for ixset-typed-0.5.1.0..
ixset-typed> [1 of 2] Compiling Data.IxSet.Typed.Ix
ixset-typed> [2 of 2] Compiling Data.IxSet.Typed
ixset-typed> 
ixset-typed> /private/var/folders/pk/z3602r3d6y55jk951blrmb8c0000gn/T/stack-72aec8c764769f60/ixset-typed-0.5.1.0/src/Data/IxSet/Typed.hs:562:42: error: [GHC-83865]
ixset-typed>     • Couldn't match type ‘BndrVis’ with ‘()’
ixset-typed>       Expected: [TyVarBndr ()]
ixset-typed>         Actual: [TyVarBndr BndrVis]
ixset-typed>     • In the second argument of ‘map’, namely ‘binders’
ixset-typed>       In the expression: map tyVarBndrToName binders
ixset-typed>       In an equation for ‘names’: names = map tyVarBndrToName binders
ixset-typed>     |
ixset-typed> 562 |              names = map tyVarBndrToName binders
```

**Comment by lolepezy** [comment]
Builds normally with GHC 9.6 though and earlier

**Comment by lolepezy** [comment]
I will close the issue, since it build on master and just needs a release on hackage
