### ISSUE TITLE
GHC 8.4 compatibility

### ISSUE THREAD

**Issue by clinty** [well-typed/ixset-typed#8]
Please bump template-haskell upper bound and whatever else is necessary to get this to build with GHC 8.4.

**Comment by clinty** [comment]
```
src/Data/IxSet/Typed.hs:1:36: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE UndecidableInstances, OverlappingInstances, FlexibleInstances,
  |                                    ^^^^^^^^^^^^^^^^^^^^

src/Data/IxSet/Typed/Ix.hs:1:36: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE UndecidableInstances, OverlappingInstances, FlexibleInstances,
  |                                    ^^^^^^^^^^^^^^^^^^^^
[1 of 2] Compiling Data.IxSet.Typed.Ix ( src/Data/IxSet/Typed/Ix.hs, dist/dist-sandbox-c883d093/build/Data/IxSet/Typed/Ix.o )

src/Data/IxSet/Typed/Ix.hs:79:20: warning: [-Wdeprecations]
    In the use of ‘insertWith'’ (imported from Data.Map):
    Deprecated: "As of version 0.5, replaced by 'Data.Map.Strict.insertWith'."
   |
79 | insert k v index = Map.insertWith' Set.union k (Set.singleton v) index
   |                    ^^^^^^^^^^^^^^^
[2 of 2] Compiling Data.IxSet.Typed ( src/Data/IxSet/Typed.hs, dist/dist-sandbox-c883d093/build/Data/IxSet/Typed.o )

src/Data/IxSet/Typed.hs:414:1: error:
    • Potential superclass cycle for ‘Indexable’
        one of whose superclass constraints is headed by a type family:
          ‘All Ord ixs’
      Use UndecidableSuperClasses to accept this
    • In the class declaration for ‘Indexable’
    |
414 | class (All Ord ixs, Ord a) => Indexable ixs a where
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by kosmikus** [comment]
Yes, I'll look into this.

**Comment by kosmikus** [comment]
@clinty What version are you compiling though? The `OverlappingInstances` and `UndecidableSuperClasses` problems are long fixed.

**Comment by kosmikus** [comment]
I just release ixset-typed-0.4 which should have compatiblity with GHC 8.4.
